### ISSUE TITLE
[Team] [Social Media] Data Appearing Twice

### ISSUE THREAD

**Issue by piedcipher** [GDGAhmedabad/devfestahm#239]
<img src='https://github.com/GDGAhmedabad/devfestahm/assets/13456345/12b18a6e-9945-4083-ae73-5ac9b91908c3' width=300>

"Bharat Makwana" is appearing twice in the social media team list. I tried searching the occurrence in the code but couldn't find it, I think it's remote data source.

**Comment by JaldeepAsodariya** [comment]
Thanks for the bug report. I will re-run database script and it will fix this.
