### ISSUE TITLE
Job Openings for Tecmantras Solution

### ISSUE THREAD

**Issue by biren-tecmantras** [GDGAhmedabad/devfestahm#262]

**Comment by PareshMayani** [comment]
@biren-tecmantras You actually need to create a pull request using the given details.
======
Add your company's job opportunities
Follow steps mentioned over the Github repository https://github.com/GDGAhmedabad/devfestahm#list-job-opportunities-of-the-companies

**Comment by biren-tecmantras** [comment]
Hi @PareshMayani 
I am still not a contributor into this repo.
So if I am trying to create a branch and try to push a commit from local to server, it is giving me an error of 403.
So could you please guide how can I get access to push my branch, so after that I can create a pull request.

Error is coming:
Failed to push to the remote repository. See the Output window for more details.
Pushing tecmantras/tecmantras-opening
Remote: Permission to GDGAhmedabad/devfestahm.git denied to biren-tecmantras.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/GDGAhmedabad/devfestahm.git/': The requested URL returned error: 403
