### ISSUE TITLE
Not able to create a branch into the repo

### ISSUE THREAD

**Issue by biren-tecmantras** [GDGAhmedabad/devfestahm#403]
Hi @PareshMayani 
I am still not a contributor into this repo.
So if I am trying to create a branch and try to push a commit from local to server, it is giving me an error of 403.
So could you please guide how can I get access to push my branch, so after that I can create a pull request.

Error is coming:
Failed to push to the remote repository. See the Output window for more details.
Pushing tecmantras/tecmantras-opening
Remote: Permission to GDGAhmedabad/devfestahm.git denied to biren-tecmantras.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/GDGAhmedabad/devfestahm.git/': The requested URL returned error: 403

_Originally posted by @biren-tecmantras in https://github.com/GDGAhmedabad/devfestahm/issues/262#issuecomment-2469928138_

**Comment by PareshMayani** [comment]
@biren-tecmantras I'm sure you have read the instructions, if not then please read and follow the steps https://devfest.gdgahmedabad.com/job-openings
